apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "octophp.fullname" . }}-env
data:
  laravelEnv: |
    APP_NAME=octophp
    APP_ENV={{.Values.appEnv}}
    APP_KEY=base64:1TVpqIAREk+OvnxQDo20LrTTwKWmjc+pwlbQ+v0OlU0=
    APP_DEBUG=true
    APP_URL=http://localhost
    LOG_CHANNEL=stack
    LOG_LEVEL=debug
    DB_CONNECTION={{.Values.db.type}}
    DB_HOST={{ include "octophp.fullname" . }}-db
    DB_PORT={{.Values.db.service.port}}
    DB_DATABASE={{.Values.db.name}}
    DB_USERNAME={{.Values.db.user}}
    DB_PASSWORD={{.Values.db.password}}
    REDIS_HOST={{ include "octophp.fullname" . }}-redis
    REDIS_PASSWORD={{.Values.redis.password}}
    REDIS_PORT={{.Values.redis.service.port}}
