apiVersion: apps/v1
kind:  StatefulSet
metadata:
  name: {{ include "octophp.fullname" . }}-db
  labels:
    {{- include "octophp.labels" . | nindent 4 }}-db
spec:
  replicas: {{ .Values.db.replicaCount }}
  selector:
    matchLabels:
      {{- include "octophp.selectorLabels" . | nindent 6 }}-db
  template:
    metadata:
      {{- with .Values.db.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "octophp.selectorLabels" . | nindent 8 }}-db
    spec:
      {{- with .Values.db.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "octophp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.db.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.db.securityContext | nindent 12 }}
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.db.image.pullPolicy }}
          env:
          - name: MYSQL_USER
            value: {{.Values.db.user}}
          - name: MYSQL_PASSWORD
            value: {{.Values.db.password}}
          - name: MYSQL_DATABASE
            value: {{.Values.db.name}}
          - name: MYSQL_RANDOM_ROOT_PASSWORD
            value:  "yes"
          ports:
            - name: http
              containerPort: {{ .Values.db.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.db.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.db.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.db.resources | nindent 12 }}
          {{- with .Values.db.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.db.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.db.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.db.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.db.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
