apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    meta.helm.sh/release-name: test
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2024-05-18T14:19:47Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: octophp
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: octophp-0.1.0
  name: test-octophp-db
  namespace: default
  resourceVersion: "5512"
  uid: 62b2b2d4-aeaf-44f5-88aa-6f3294de94e5
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-db
      app.kubernetes.io/name: octophp
  serviceName: ""
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-db
        app.kubernetes.io/name: octophp
    spec:
      containers:
      - env:
        - name: MYSQL_USER
          value: laravel
        - name: MYSQL_PASSWORD
          value: D4$vXsz2C
        - name: MYSQL_DATABASE
          value: octophpdb
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: "yes"
        image: docker.io/mysql:8.0
        imagePullPolicy: IfNotPresent
        name: octophp
        ports:
        - containerPort: 3306
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 3306
          timeoutSeconds: 1
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: test-octophp
      serviceAccountName: test-octophp
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
status:
  availableReplicas: 1
  collisionCount: 0
  currentReplicas: 1
  currentRevision: test-octophp-db-cc76b4bf9
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updateRevision: test-octophp-db-cc76b4bf9
  updatedReplicas: 1
