apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: test
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2024-05-18T14:19:47Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: octophp
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: octophp-0.1.0
  name: test-octophp-redis
  namespace: default
  resourceVersion: "5493"
  uid: f6c58a58-1b67-4cf4-a683-03b1d0833d34
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-redis
      app.kubernetes.io/name: octophp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-redis
        app.kubernetes.io/name: octophp
    spec:
      containers:
      - env:
        - name: REDIS_PASSWORD
          value: a38C8v@#vs
        image: docker.io/redis:alpine3.19
        imagePullPolicy: IfNotPresent
        name: octophp
        ports:
        - containerPort: 6379
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 6379
          timeoutSeconds: 1
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: test-octophp
      serviceAccountName: test-octophp
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-05-18T14:20:00Z"
    lastUpdateTime: "2024-05-18T14:20:00Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-05-18T14:19:47Z"
    lastUpdateTime: "2024-05-18T14:20:00Z"
    message: ReplicaSet "test-octophp-redis-fd58b98f5" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
